# Generated by Django 4.1.1 on 2022-10-12 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('rooms', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('kitchen', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('living_room', models.BooleanField(default=True)),
                ('furnishing', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default='')),
                ('available_from', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('available_to', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('available_to_undefined', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unspecified', max_length=20)),
                ('image', models.ImageField(default='', upload_to='apartment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('long', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_images')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_image', to='room_service.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_service.apartmentcontact'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_service.apartmenttype'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='features',
            field=models.ManyToManyField(blank=True, to='room_service.apartmentfeature'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_service.location'),
        ),
    ]
