# Generated by Django 4.1.1 on 2022-10-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='bedrooms',
        ),
    ]
