# Generated by Django 4.0.5 on 2022-07-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
