# Generated by Django 4.0.5 on 2022-07-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0002_alter_location_city_alter_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ApartmentType',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room_service.apartmenttype'),
            preserve_default=False,
        ),
    ]
