# Generated by Django 4.1.1 on 2022-10-26 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0002_remove_apartment_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='furnishing',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='living_room',
        ),
        migrations.AddField(
            model_name='apartment',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='apartmentfeature',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
    ]
