# Generated by Django 4.0.5 on 2022-07-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0003_rename_type_apartmenttype_apartment_apartment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttype',
            name='name',
            field=models.CharField(default='Unspecified', max_length=20),
        ),
    ]
