# Generated by Django 4.1.1 on 2022-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0003_remove_apartment_furnishing_remove_apartment_garage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
