# Generated by Django 4.0.5 on 2022-07-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0005_apartment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment_images')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_service.apartment')),
            ],
        ),
    ]
