# Generated by Django 4.0.5 on 2022-07-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0007_location_address_alter_apartmentimage_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmenttype',
            name='image',
            field=models.ImageField(default='', upload_to='apartment_type'),
        ),
    ]
